server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microserivice-jourmey
            uri: lb://microservice-journey
            predicates:
              - Path=/api/journeys/**
          - id: microserivice-maintenance
            uri: lb://microservice-maintenance
            predicates:
              - Path=/api/maintenances/**
          - id: microservice-monopatin
            uri: lb://microservice-monopatin
            predicates:
              - Path=/api/monopatines/**
          - id: microservice-payment
            uri: lb://microservice-payment
            predicates:
                - Path=/api/payments/**
          - id: microservice-report
            uri: lb://microservice-report
            predicates:
              - Path=/api/reports/**
          - id: microservice-user
            uri: lb://microservice-user
            predicates:
              - Path=/api/user/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

