server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: microservice-report
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/report?createDatabaseIfNotExist=true
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
