services:
  monopatindb:
    container_name: monopatin
    image: postgres:14.4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=monopatin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5434:5432"
    command: postgres -c 'log_statement=all'
