services:
  userdb:
    container_name: user
    image: postgres:14.4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=user
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5437:5432"
    command: postgres -c 'log_statement=all'
