spring:
  application:
    name: gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3307/auth?createDatabaseIfNotExist=true
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

cloud:
  gateway:
    mvc:
      routes:
        - id: microservice-journey
          uri: http://localhost:8051
          predicates:
            - Path=/api/journeys/**,/api/fees/**,/api/pauses/**

        - id: microservice-maintenance
          uri: http://localhost:8053
          predicates:
            - Path=/api/maintenances/**

        - id: microservice-monopatin
          uri: http://localhost:8052
          predicates:
            - Path=/api/monopatines/**,/api/stops/**

        - id: microservice-user
          uri: http://localhost:8050
          predicates:
            - Path=/api/users/**,/api/accounts/**

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

#
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
