 spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8081
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3307/auth?createDatabaseIfNotExist=true
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  cloud:
   gateway:
     routes:
       - id: microservice-journey
         uri: lb://microservice-journey:8051
         predicates:
           - Path=/api/journeys/**
           - Path=/api/fees/**
           - Path=/api/pauses/**

       - id: microservice-maintenance
         uri: lb://microservice-maintenance:8053
         predicates:
           - Path=/api/maintenances/**

       - id: microservice-monopatin
         uri: lb://microservice-monopatin:8052
         predicates:
           - Path=/api/monopatines/**
           - Path=/api/stops/**

       - id: microservice-user
         uri: lb://microservice-user:8050
         predicates:
           - Path=/api/users/**
           - Path=/api/accounts/**

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
